# Generated by Django 5.2 on 2025-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='obtained',
            field=models.BooleanField(default=False, help_text='Indicates whether the item has been obtained.'),
        ),
    ]
