# Generated by Django 5.2 on 2026-02-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_family_membership_customuser_families'),
        ('shoppinglist', '0003_item_created_item_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='project.family'),
            preserve_default=False,
        ),
    ]
