# Generated by Django 5.2 on 2026-02-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('project', '0003_family_membership_customuser_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='project.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='project.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='project.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='project.family'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('family', 'name')},
        ),
    ]
