# Generated by Django 5.2 on 2025-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='child',
            field=models.BooleanField(default=True),
        ),
    ]
