# Generated by Django 5.2 on 2026-02-18 17:19

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_customuser_bio_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.user_profile_pic_path),
        ),
    ]
