# Generated by Django 5.2 on 2026-02-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_message_sender'),
        ('project', '0003_family_membership_customuser_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.family'),
            preserve_default=False,
        ),
    ]
