# Generated by Django 5.2 on 2025-05-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demerit',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='merit',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
