# Generated by Django 5.2 on 2025-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('false', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-monthly', 'Bi-Monthly'), ('semi-annually', 'Semi-Annually'), ('annually', 'Annually')], default='false', max_length=20),
        ),
    ]
